Repository codestates-seb/seb42_main_021, pull requests merged in 2023-03, with the labels that each got.

#3 chore: Spring Application initializr
  server/EverybodyChachapark/.gitignore
  server/EverybodyChachapark/build.gradle
  server/EverybodyChachapark/gradle/wrapper/gradle-wrapper.jar
  server/EverybodyChachapark/gradle/wrapper/gradle-wrapper.properties
  server/EverybodyChachapark/gradlew
  server/EverybodyChachapark/gradlew.bat
  server/EverybodyChachapark/settings.gradle
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/EverybodyChachaparkApplication.java
  server/EverybodyChachapark/src/main/resources/application.yml
  server/EverybodyChachapark/src/test/java/com/DuTongChitongYutong/EverybodyChachapark/EverybodyChachaparkApplicationTests.java
  server/README.md
  server/build.gradle
  server/settings.gradle
  server/src/main/resources/application.properties
Labels: back-end

#19 feat: Review기능 API 명세서 생성
  server/EverybodyChachapark/src/docs/asciidoc/EverbodyChachapark.adoc
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/EverybodyChachaparkApplication.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/SecurityConfiguration.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/review/controller/ReviewController.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/review/dto/ReivewDto.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/response/MultiResponseDto.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/response/PageInfo.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/response/SingleResponseDto.java
  server/EverybodyChachapark/src/main/resources/static/docs/EverbodyChachapark.html
  server/EverybodyChachapark/src/test/java/com/DuTongChitongYutong/EverybodyChachapark/slice/review/ReviewControllerTest.java
  server/EverybodyChachapark/src/test/java/com/DuTongChitongYutong/EverybodyChachapark/util/ApiDocumentUtils.java
Labels: back-end, feature

#45 [Feat] 상품 기능 1차 구현
  .idea/seb42_main_021.iml
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/SecurityConfiguration.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/order/controller/OrderController.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/order/dto/OrderCancelDto.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/order/dto/OrderDto.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/order/dto/OrderPostDto.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/order/dto/OrderProductCancelDto.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/order/dto/OrderProductDto.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/order/dto/OrderProductPostDto.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/order/entity/Order.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/order/entity/OrderProduct.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/order/entity/OrderpProductStatus.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/order/repository/OrderRepository.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/order/service/OrderService.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/product/controller/ProductController.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/product/dto/ProductDto.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/product/dto/ProductPatchDto.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/product/dto/ProductPostDto.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/product/entity/Product.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/product/entity/ProductCategory.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/product/entity/ProductStatus.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/product/facade/ProductFacade.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/product/repository/ProductRepository.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/product/service/ProductService.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/response/MultiResponseDto.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/response/SingleResponseDto.java
Labels: back-end, feature

#54 [Feat] Cart 로직 완성
  server/.idea/compiler.xml
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/cart/controller/CartController.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/cart/dto/CartDto.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/cart/entity/Cart.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/cart/fasade/CartFacade.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/cart/repository/CartRepository.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/cart/service/CartService.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/member/entity/Member.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/member/service/MemberService.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/product/service/ProductService.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/review/entity/Review.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/security/configure/CustomFilterConfigurer.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/security/configure/SecurityConfiguration.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/security/jwt/JwtAuthenticationFilter.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/security/jwt/JwtVerificationFilter.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/security/service/MemberDetailsService.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/security/utils/CustomAuthorityUtils.java
  server/EverybodyChachapark/src/main/resources/application.yml
Labels: back-end

#55 Feat/be/product
  server/EverybodyChachapark/src/docs/asciidoc/EverbodyChachapark.adoc
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/product/controller/ProductController.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/product/dto/ProductDto.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/product/dto/ProductPostDto.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/product/entity/Product.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/product/entity/ProductCategory.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/product/facade/ProductFacade.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/product/service/ProductService.java
  server/EverybodyChachapark/src/test/java/com/DuTongChitongYutong/EverybodyChachapark/slice/product/ProductControllerTest.java
Labels: back-end, feature

#64 [Feat] Cart docs 추가
  server/EverybodyChachapark/src/docs/asciidoc/EverbodyChachapark.adoc
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/cart/controller/CartController.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/cart/dto/CartDto.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/cart/entity/Cart.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/cart/fasade/CartFacade.java
  server/EverybodyChachapark/src/test/java/com/DuTongChitongYutong/EverybodyChachapark/slice/cart/CartControllerTest.java
Labels: back-end

#67 [Feat] 회원 comment 로직 추가
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/member/dto/MemberDto.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/member/entity/Member.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/member/mapper/MemberMapper.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/member/service/MemberService.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/security/dto/LoginDto.java
  server/EverybodyChachapark/src/test/java/com/DuTongChitongYutong/EverybodyChachapark/slice/member/MemberControllerTest.java
  server/EverybodyChachapark/src/test/java/com/DuTongChitongYutong/EverybodyChachapark/slice/security/CustomFilterConfigurerTest.java
Labels: back-end

#68 Feat/be/product
  server/EverybodyChachapark/src/docs/asciidoc/EverbodyChachapark.adoc
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/order/dto/OrderProductDto.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/order/entity/OrderProduct.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/order/entity/OrderProductStatus.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/product/controller/ProductController.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/product/dto/ProductDto.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/product/dto/ProductPatchDto.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/product/dto/ProductPostDto.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/product/entity/Product.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/product/entity/ProductCategory.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/product/facade/ProductFacade.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/product/repository/ProductRepository.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/product/service/ProductService.java
  server/EverybodyChachapark/src/test/java/com/DuTongChitongYutong/EverybodyChachapark/slice/product/ProductControllerTest.java
Labels: back-end, feature

#82 [Back-end] 보안 및 회원로직 수정
  server/EverybodyChachapark/build.gradle
  server/EverybodyChachapark/src/docs/asciidoc/EverbodyChachapark.adoc
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/cart/service/CartService.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/member/controller/MemberController.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/member/dto/MemberDto.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/member/mapper/MemberMapper.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/member/repository/MemberRepository.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/member/service/MemberService.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/exception/ExceptionCode.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/security/configure/CustomFilterConfigurer.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/security/configure/RedisConfig.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/security/configure/SecurityConfiguration.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/security/dto/LoginDto.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/security/exception/AuthExceptionCode.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/security/exception/SecurityAuthException.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/security/hendler/MemberAuthenticationFailureHandler.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/security/hendler/MemberAuthenticationSuccessHandler.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/security/jwt/JwtAuthenticationFilter.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/security/jwt/JwtTokenizer.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/security/jwt/JwtVerificationFilter.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/security/repository/RefreshTokenRepository.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/security/service/MemberDetailsService.java
  server/EverybodyChachapark/src/main/resources/application.yml
  server/EverybodyChachapark/src/test/java/com/DuTongChitongYutong/EverybodyChachapark/slice/cart/CartControllerTest.java
  server/EverybodyChachapark/src/test/java/com/DuTongChitongYutong/EverybodyChachapark/slice/member/MemberControllerTest.java
Labels: back-end

#106 주문 기능 구현
  server/EverybodyChachapark/src/docs/asciidoc/EverbodyChachapark.adoc
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/EverybodyChachaparkApplication.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/order/controller/OrderController.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/order/dto/OrderCancelDto.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/order/dto/OrderDto.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/order/dto/OrderPostDto.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/order/dto/OrderProductCancelDto.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/order/dto/OrderProductDto.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/order/dto/OrderProductPostDto.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/order/entity/Order.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/order/entity/OrderProduct.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/order/entity/OrderStatus.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/order/repository/OrderRepository.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/order/service/OrderService.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/product/facade/ProductFacade.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/exception/ExceptionCode.java
  server/EverybodyChachapark/src/test/java/com/DuTongChitongYutong/EverybodyChachapark/slice/order/OrderControllerTest.java
  server/EverybodyChachapark/src/test/java/com/DuTongChitongYutong/EverybodyChachapark/slice/product/ProductControllerTest.java
Labels: back-end, feature

#118 [Back-end] 상품 권한 수정
  server/EverybodyChachapark/build.gradle
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/configure/CustomFilterConfigurer.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/configure/RedisConfig.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/configure/SecurityConfiguration.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/controller/RefreshTokenController.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/dto/LoginDto.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/hendler/MemberAccessDeniedHandler.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/hendler/MemberAuthenticationEntryPoint.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/hendler/MemberAuthenticationFailureHandler.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/hendler/MemberAuthenticationSuccessHandler.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/hendler/Oauth2MemberSuccessHandler.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/jwt/JwtAuthenticationFilter.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/jwt/JwtTokenizer.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/jwt/JwtVerificationFilter.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/repository/RefreshTokenRepository.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/service/MemberDetailsService.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/utils/CustomAuthorityUtils.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/utils/ErrorResponder.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/cart/fasade/CartFacade.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/member/service/MemberService.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/security/dto/LoginDto.java
  server/EverybodyChachapark/src/main/resources/application.yml
  server/EverybodyChachapark/src/main/resources/static/docs/EverbodyChachapark1.7.html
  server/EverybodyChachapark/src/test/java/com/DuTongChitongYutong/EverybodyChachapark/slice/security/CustomFilterConfigurerTest.java
Labels: back-end

#121 [Feat] oauth2 적용
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/configure/SecurityConfiguration.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/hendler/Oauth2MemberSuccessHandler.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/member/controller/MemberController.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/member/dto/MemberDto.java
Labels: back-end

#130 [Back-end] oAuth2 권한수정
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/configure/SecurityConfiguration.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/hendler/Oauth2MemberSuccessHandler.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/cart/dto/CartDto.java
Labels: back-end

#132 [Back-end] Oauth2 호스트 주소 변경
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/hendler/Oauth2MemberSuccessHandler.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/jwt/JwtVerificationFilter.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/cart/entity/Cart.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/cart/fasade/CartFacade.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/member/service/MemberService.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/order/service/OrderService.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/exception/ExceptionCode.java
Labels: back-end

#135 Feat/be/order 주문 기능 수정
  server/EverybodyChachapark/src/docs/asciidoc/EverbodyChachapark.adoc
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/order/controller/OrderController.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/order/dto/OrderListPage.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/order/repository/OrderRepository.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/order/service/OrderService.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/product/facade/ProductFacade.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/exception/ExceptionCode.java
  server/EverybodyChachapark/src/test/java/com/DuTongChitongYutong/EverybodyChachapark/slice/order/OrderControllerTest.java
Labels: back-end, feature

#141 [Back-end] oauth2 경로변경
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/hendler/Oauth2MemberSuccessHandler.java
Labels: back-end

#157 [Fix] 배포 성공, CORS 문제 해결
  client/src/components/login/useLogin.js
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/configure/SecurityConfiguration.java
  server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/jwt/JwtAuthenticationFilter.java
Labels: bug
